apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker
        image: docker.io/larbizyoisco/worker-app:sha-37bb837
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
